import { Inter } from "next/font/google"
import "../globals.css"
import GlobalLayout from "../_components/GlobalLayout"
import DashboardProvider from "../_providers/DashboardContext"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalLayout>
          <DashboardProvider>{children}</DashboardProvider>
        </GlobalLayout>
      </body>
    </html>
  )
}
